### ISSUE TITLE
z tm  # Jump to `*tm*`

### ISSUE THREAD

**Issue by jgarte** [anki-code/xontrib-jump-to-dir#2]
Hi,

What does `*tm*` in the README mean?

Is there a `*tm*` variable that is defined somewhere?

> z tm  # Jump to `*tm*`

**Comment by anki-code** [comment]
Jump to directory with `*tm*` in path e.g. `/tmp/`

**Comment by jgarte** [comment]
Hi, how does it know that `*tm*` is `/tmp/`? 

Is it because you typed it earlier and it remembered it or it expands somehow because the letters `tm` are in `/tmp/`?

That wasn't clear for me.

**Comment by jgarte** [comment]
> Jump to directory with *tm* in path e.g. /tmp/

I opened a PR that further disambiguates what I was confused about in the context of the above comment that you referenced from the README:

```
Jump to previous directory with *tm* in path e.g. /tmp/
```

**Comment by anki-code** [comment]
In short it works like describe in the SQL query - https://github.com/anki-code/xontrib-jump-to-dir/blob/f6681e175692cb3ba7f2f0d716a52fc02e08d5d6/xontrib/jump_to_dir.py#L16-L19

I've added How it works section - https://github.com/anki-code/xontrib-jump-to-dir/blob/main/README.md#how-it-works
